Improved folder and file check

diff --git a/.github/workflows/validate-macsetup.yaml b/.github/workflows/validate-macsetup.yaml
--- a/.github/workflows/validate-macsetup.yaml
+++ b/.github/workflows/validate-macsetup.yaml
@@ -7,7 +7,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-latest, macos-11]
+        os: [macos-latest]
         arch: [x64, arm64]
       fail-fast: false
 
@@ -59,7 +59,7 @@ jobs:
             exit 1
           fi
           echo "folder and file exists"
-          tools=$(jq -c '.[]' "$macsetup_dir/tools.json")
+          tools=$(jq -c '.[]' "$macsetup_dir/tools.json" || { echo "Failed to parse tools.json"; exit 1; })
           for tool in $tools; do
             name=$(echo "$tool" | jq -r '.name')
             verify_command=$(echo "$tool" | jq -r '.verify_command')
